print("end of line ")
print('a\nb\nc')
print("carriage return")
print('a\rb\rc')
print("form feed")
print('a\fb\fc')
print("vertical tab")
print('a\vb\vc')
print("horizontal tab")
print('a\tb\tc')
print("backspace")
print('a\bb\bc')
print("alert")
print('a\ab\ac')